title: Evan Lamb # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor of Science in Aerospace Engineering (B.S.E)
  Minor in Spanish Language
  Graduated 2020 Summa Cum Laude
  <br><br>
  <a href="https://www.linkedin.com/in/e-lamb">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
